name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build -- --prod

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Setup Google Cloud SDK
      uses: actions/setup-gcloud@v0.5.0
      with:
        project_id: idk-movies
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GCP App Engine
      run: gcloud app deploy --quiet
